artigos/urls.py
from django.urls import path

from . import views

# articles:article
app_name = 'articles'

urlpatterns = [
    path('', views.home, name='home'),
    path('articles/search/', views.search, name='search'),
    path('articles/category/<int:category_id>/',
         views.category, name='category'),
    path('articles/<int:id>/', views.article, name='article'),
]

sp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('artigos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

artigos/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self) -> str:
        return self.name


class Difficulty(models.Model):
    difficulty = models.CharField(max_length=65)
    units = models.IntegerField()

    def __str__(self) -> str:
        return self.difficulty


class Article(models.Model):
    title = models.CharField(max_length=90)
    description = models.CharField(max_length=190)
    slug = models.SlugField(unique=True)
    difficulty = models.ForeignKey(
        Difficulty, on_delete=models.SET_NULL, null=True)
    text = models.TextField()
    text_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='articles/covers/%Y/%m/%d/', blank=True, null=True,
        default='articles/covers/%Y/%m/%d/default_article_cover.jpg')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL,
        null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    link = models.URLField(max_length=250, null=True)

    def __str__(self) -> str:
        return self.title

artigos/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.template.response import TemplateResponse

from artigos.models import Article


# Create your views here.
def home(request, template_name="artigos/pages/home.html"):
    articles = Article.objects.filter(is_published=True).order_by('-id')
    current_page = request.GET.get('page', 1)
    paginator = Paginator(articles, 8)
    page_obj = paginator.get_page(current_page)
    args = {}
    name = "Cesar Luiz Ferracin"
    args['name'] = name
    args['articles'] = page_obj

    return TemplateResponse(request, template_name, args)


def category(request, category_id, template_name="artigos/pages/category.html"):
    articles_db = get_list_or_404(Article.objects.filter(
        category__id=category_id, is_published=True).order_by('-id'))
    articles = articles_db
    args = {}
    args['name'] = "Cesar Luiz Ferracin"
    args['articles'] = articles
    args['title'] = f'{articles[0].category.name} - Category | '
    return TemplateResponse(request, template_name, args)


def article(request, id):
    article = get_object_or_404(Article, pk=id, is_published=True)
    args = {}
    args['name'] = "Cesar Luiz Ferracin"
    args['article'] = article
    args['is_detail_page'] = True
    return render(request, 'artigos/pages/artigo-view.html', args)


def search(request):
    search_term = request.GET.get('q', '').strip()
    if not search_term:
        raise Http404()

    articles = Article.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ),
        is_published=True
    ).order_by('-id')

    return render(request, 'artigos/pages/search.html', {
        'page_title': f'Pesquisa por "{search_term}" |',
        'search_term': search_term,
        'articles': articles,
    })

sp/views.py
# Create your views here.

artigos/templates/artigos/pages/artigo-view.html
{% extends 'global/base.html' %}

{% block title %} {{article.title}} {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'artigos/partials/article.html' %}           
</div>
{% endblock content %}

artigos/templates/artigos/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for article in articles %}
        {% include 'artigos/partials/article.html' %}
    {% endfor %}
</div>
{% endblock content %}         

artigos/templates/artigos/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for article in articles %}
        {% include 'artigos/partials/article.html' %}
    {% empty %}
        <div class="center m-y">
            <h1>No articles found here 🥲</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}         

artigos/templates/artigos/pages/search.html
{% extends 'global/base.html' %}

{% block title %}{{page_title}} {% endblock title %}

{% block content %}

<div class="main-content main-content-list container">
    {% for article in articles %}
        {% include 'artigos/partials/article.html' %}
    {% empty %}
        <div class="center m-y">
            <h1>No articles found here 🥲</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}  

artigos/templates/artigos/partials/article.html
<div class="article article-list-item">
    <div class="article-cover">
        <a href="{% url 'articles:article'  article.id  %}">
            <img src="{{ article.cover.url }}" alt="Temporário">
        </a>
    </div>
    <div class="article-title-container">
        <h2 class="article-title">
            <a href="{% url 'articles:article'  article.id  %}">
                {{ article.title }}</h2>
            </a>
    </div>
    <div class="article-author">
        {% if article.author is not None %}
            <span class="article-author-item">
                <i class="fas fa-user"></i>
                    {% if article.author.first_name %}
                        {{ article.author.first_name }} {{ article.author.last_name }}
                    {% else %}
                        {{ article.author.username }} 
                    {% endif %}
            </span>
        {% endif %}

        <span class="article-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ article.created_at|date:"d/m/Y" }} às {{ article.created_at|date:"H:i:s" }}
        </span>
    {% if article.category is not None %}
        <span class="article-author-item">
            <a href="{% url 'articles:category' article.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span class="">{{ article.category.name }}</span>
            </a>
        </span>   
    {% endif %}                 
    </div>
    <div class="article-content">
        <p>{{ article.description }}</p>
    </div>

    <div class="article-meta-container">
        <div class="article-meta article-difficulty">
            <h3 class="article-meta-title">
                <i class="fas fa-stopwatch"></i>
                Dificuldade
            </h3>
            <div class="article-meta-text">{{ article.difficulty.difficulty }}</div>
        </div>
        <div class="article-meta article-subject">
            <h3 class="article-meta-title">
                <i class="fas fa-stopwatch"></i>
                Assunto
            </h3>
            <div class="article-meta-text">{{ article.category.name }}</div>
        </div>                   
    </div>     
    {% if is_detail_page is not True %}    
    <footer class="article-footer">
        <a href="{% url 'articles:article'  article.id  %}" class="article-read-more button button-dark button-full-width">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>        
    {% endif %}     
    {% if is_detail_page is True %}    
        <div class="article-text">
        {% if article.text_is_html is True %}   
            {{ article.text | safe }}    
        {% else %}   
            {{ article.text | linebreaksbr }}           
        {% endif %}           
        </div> 
    {% endif %}                
</div>

artigos/templates/artigos/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.cesarferracin.com.br/" target="_blank" rel="noreferrer noopener">By Cesar Ferracin</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

artigos/templates/artigos/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
    integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css"
    integrity="sha512-OivR4OdSsE1onDm/i3J3Hpsm5GmOVvr9r49K3jJ0dnsxVzZgaOJ5MfxEAxCyGrzWozL9uJGKz6un3A7L+redIQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/solid.min.css"
    integrity="sha512-qzgHTQ60z8RJitD5a28/c47in6WlHGuyRvMusdnuWWBB6fZ0DWG/KyfchGSBlLVeqAz+1LzNq+gGZkCSHnSd3g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'artigos/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">

artigos/templates/artigos/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'articles:home' %}">
                <i class="fas fa-chalkboard main-logo-icon"></i>
                <span class="main-logo-text">Sobretudo Português</span>
            </a>
        </h1>
        <h3>
            <a class="articles-logo" href="{% url 'articles:home' %}">                
                <i class="fas fa-chalkboard articles-logo-icon"></i>
                <span class="articles-logo-text">Artigos</span>    
            </a>
        </h3>
        <h4>
            <a class="author-logo" href="{% url 'articles:home' %} ">                
                <i class="fas fa-circle-user author-logo-icon"></i>
                <span class="articles-author-text">Por {{ name }}</span>   
            </a>                
        </h4>
    </div>
</header>

artigos/templates/artigos/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'articles:search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>